/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nickheitzman (https://sketchfab.com/nickheitzman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-puzzle-islands-243d208c0bd74455800dc65f900eff21
Title: The Puzzle Islands
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';  
import {a} from '@react-spring/three';

import islandScene from '../assets/3d/the_puzzle_islands.glb';


const Island = ({isRotating, setIsRotating, setCurrentStage, ...props}) => {
  const islandRef = useRef(); //Hook to access the island model

  const {gl, viewport} = useThree(); //Hook to access the viewport
  const {nodes, materials} = useGLTF(islandScene); //Hook to access the island model  


  const lastX = useRef(0); //Hook to store the last x position of the mouse 
  const rotationSpeed = useRef(0); //Hook to store the rotation speed of the island
  const dampingFactor = 0.95; //Damping factor for the rotation speed

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;

    lastX.current = clientX;
  } 

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);

  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if(isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;
  
      islandRef.current.rotation.y += delta * Math.PI * 0.01;
      lastX.current = clientX;
      rotationSpeed.current = delta *0.01 * MATH.PI;
    }
  }

  const handleKeyDown = (e) => {
    if(e.key === 'ArrowLeft ') {
      if(!isRotating) setIsRotating(true);
      islandRef.current.rotation.y += 0.01 * Math.PI;
    } else if(e.key === 'ArrowRight') {
      if(!isRotating) setIsRotating(true);
      islandRef.current.rotation.y -= 0.01 * Math.PI;
    } 
  }

  const handleKeyUp = (e) => {
    if(e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      setIsRotating(false);
    } 
  }

  useFrame(() => {
    if(!isRotating) {
      rotationSpeed.current *= dampingFactor;
      
      if(Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;

      const normalizedRotation =
      ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI); //calculates the remainder of the rotation value when divided by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.

    // Set the current stage based on the island's orientation
    switch (true) {
      case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
        setCurrentStage(4);
        break;
      case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
        setCurrentStage(3);
        break;
      case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
        setCurrentStage(2);
        break;
      case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
        setCurrentStage(1);
        break;
      default:
        setCurrentStage(null);
     }
   }
 });
   

  useEffect (() => {
    const canvas = gl.domElement; //Get the canvas element from the WebGL renderer
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('pointerup', handlePointerUp);
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointermove', handlePointerMove);
      canvas.removeEventListener('pointerup', handlePointerUp);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    }; 
  },
   [gl, handlePointerDown, handlePointerMove, handlePointerUp]);


  return (
    <a.group ref={islandRef} {...props} >
          <mesh
            
            
            geometry={nodes.pCylinder7_Decor_0.geometry}
            material={materials.Decor}
          />
          <mesh
            
            
            geometry={nodes.pCylinder7_lambert1_0.geometry}
            material={materials.lambert1}
          />
      
     
         
          <mesh
            
            
            geometry={nodes.pCylinder13_Decor_0.geometry}
            material={materials.Decor}
          />
          <mesh
            
            
            geometry={nodes.pCylinder13_lambert1_0.geometry}
            material={materials.lambert1}
          />
      
        <mesh
          
          
          geometry={nodes.polySurface2_Island_0.geometry}
          material={materials.Island}
        />
        <mesh
          
          
          geometry={nodes.pCube1_Ocean_0.geometry}
          material={materials.Ocean}
          position={[5.492, 0, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface7_Island_0.geometry}
          material={materials.Island}
          position={[-0.657, 0, -5.032]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface8_Island_0.geometry}
          material={materials.Island}
        />
        <mesh
          
          
          geometry={nodes.polySurface9_Island_0.geometry}
          material={materials.Island}
          position={[0.213, 0.063, 18.886]}
        />
        <mesh
          
          
          geometry={nodes.pCube3_CLoud_0.geometry}
          material={materials.CLoud}
          position={[0, -0.988, -3.099]}
        />
        <mesh
          
          
          geometry={nodes.pCube4_CLoud_0.geometry}
          material={materials.CLoud}
          position={[0.678, 0.515, -3.605]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCube5_CLoud_0.geometry}
          material={materials.CLoud}
          position={[0.212, -1.424, -5.075]}
          scale={1.319}
        />
        <mesh
          
          
          geometry={nodes.pCube6_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.021, 0, -0.4]}
        />
        <mesh
          
          
          geometry={nodes.pCube7_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.059, 0, 0.363]}
        />
        <mesh
          
          
          geometry={nodes.polySurface10_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.059, 0, 0.363]}
        />
        <mesh
          
          
          geometry={nodes.pCube34_CLoud_0.geometry}
          material={materials.CLoud}
          position={[-0.14, 0.612, -1.085]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCube35_CLoud_0.geometry}
          material={materials.CLoud}
          position={[5.562, -0.416, -6.561]}
          scale={0.844}
        />
        <mesh
          
          
          geometry={nodes.pCube36_CLoud_0.geometry}
          material={materials.CLoud}
          position={[5.155, 0.98, -5.615]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCylinder1_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCylinder10_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCube109_CLoud_0.geometry}
          material={materials.CLoud}
          position={[3.359, -2.086, -0.926]}
          scale={1.319}
        />
        <mesh
          
          
          geometry={nodes.pCube110_CLoud_0.geometry}
          material={materials.CLoud}
          position={[6.981, -0.416, 1.194]}
          scale={0.844}
        />
        <mesh
          
          
          geometry={nodes.pCube111_CLoud_0.geometry}
          material={materials.CLoud}
          position={[6.465, 0.395, 2.047]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCylinder11_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCube112_CLoud_0.geometry}
          material={materials.CLoud}
          position={[-0.763, 0.256, -1.867]}
          scale={0.713}
        />
        <mesh
          
          
          geometry={nodes.pCube113_CLoud_0.geometry}
          material={materials.CLoud}
          position={[6.602, 0.638, -4.775]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCube114_CLoud_0.geometry}
          material={materials.CLoud}
          position={[-0.963, 0.612, 2.767]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.polySurface11_Decor_0.geometry}
          material={materials.Decor}
          position={[1.235, 0, 2.037]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.pCube115_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.059, 0, -0.381]}
        />
        <mesh
          
          
          geometry={nodes.pCube116_Decor_0.geometry}
          material={materials.Decor}
          position={[-3.492, 0, 2.15]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube117_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.754, 0, 2.143]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface12_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.754, 0, 2.143]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface13_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.07, 0, 0.853]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube118_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.07, 0, -0.046]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface14_Decor_0.geometry}
          material={materials.Decor}
          position={[-3.492, 0, 1.245]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface15_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.333, 0, -0.053]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube119_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.333, 0, -0.053]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface16_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.834, 0, -2.794]}
        />
        <mesh
          
          
          geometry={nodes.pCube120_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.834, 0, -2.794]}
        />
        <mesh
          
          
          geometry={nodes.pCube130_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCube131_Decor_0.geometry}
          material={materials.Decor}
          position={[8.579, -0.794, 2.779]}
          rotation={[0.09, 1.05, 0.061]}
        />
        <mesh
          
          
          geometry={nodes.pCube132_Decor_0.geometry}
          material={materials.Decor}
          position={[9.941, 0.523, -4.192]}
          rotation={[-2.95, -0.397, 3.14]}
        />
        <mesh
          
          
          geometry={nodes.pCylinder12_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.44, 0, -3.265]}
        />
        <mesh
          
          
          geometry={nodes.polySurface17_Decor_0.geometry}
          material={materials.Decor}
          position={[-3.492, 0, -4.626]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface18_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.754, 0, -3.728]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube133_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.754, 0, -3.728]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface19_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.333, 0, -5.924]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface20_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.07, 0, -5.017]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube134_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.333, 0, -5.924]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube135_Decor_0.geometry}
          material={materials.Decor}
          position={[-3.492, 0, -3.721]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube136_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.07, 0, -5.917]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface21_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.834, 0, -8.555]}
        />
        <mesh
          
          
          geometry={nodes.pCube137_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.834, 0, -8.555]}
        />
        <mesh
          
          
          geometry={nodes.polySurface22_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.54, 0, -5.37]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.pCube138_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.54, 0, -5.37]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.pCube139_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.92, 0, -8.555]}
        />
        <mesh
          
          
          geometry={nodes.pCube140_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.834, 0, -2.062]}
        />
        <mesh
          
          
          geometry={nodes.pCube141_CLoud_0.geometry}
          material={materials.CLoud}
          position={[3.901, 0.395, -1.915]}
          scale={0.525}
        />
        <mesh
          
          
          geometry={nodes.pCube142_Decor_0.geometry}
          material={materials.Decor}
          position={[-3.052, 0, -0.283]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube143_Decor_0.geometry}
          material={materials.Decor}
          position={[-2.857, 0, -6.101]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube144_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.401, 0, -8.107]}
        />
        <mesh
          
          
          geometry={nodes.pCube145_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.03, 0, -6.611]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface23_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.03, 0, -6.611]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube146_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.258, 0, -6.611]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube147_Decor_0.geometry}
          material={materials.Decor}
          position={[0.214, 0, -5.487]}
        />
        <mesh
          
          
          geometry={nodes.polySurface24_Decor_0.geometry}
          material={materials.Decor}
          position={[1.508, 0, -3.069]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.pCube148_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.466, 0, -0.876]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface25_Decor_0.geometry}
          material={materials.Decor}
          position={[-0.625, 0, -6.127]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          
          
          geometry={nodes.pCube149_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.933, 0, -7.784]}
        />
        <mesh
          
          
          geometry={nodes.pCube150_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCube151_Decor_0.geometry}
          material={materials.Decor}
          position={[2.05, -0.222, -6.327]}
          rotation={[Math.PI / 2, 1.476, -Math.PI / 2]}
        />
        <mesh
          
          
          geometry={nodes.pCube152_Decor_0.geometry}
          material={materials.Decor}
          position={[1.856, -0.333, 2.982]}
          rotation={[-0.01, 0.651, 0.058]}
        />
        <mesh
          
          
          geometry={nodes.polySurface26_Decor_0.geometry}
          material={materials.Decor}
          position={[1.791, -0.191, -3.722]}
          rotation={[0.251, 1.38, -0.256]}
        />
        <mesh
          
          
          geometry={nodes.pCube153_Decor_0.geometry}
          material={materials.Decor}
          position={[1.794, -0.192, -3.722]}
          rotation={[0.251, 1.38, -0.256]}
        />
        <mesh
          
          
          geometry={nodes.polySurface30_Decor_0.geometry}
          material={materials.Decor}
          position={[7.65, -0.548, -13.124]}
          rotation={[3.129, 0.2, -3.084]}
        />
        <mesh
          
          
          geometry={nodes.polySurface31_Decor_0.geometry}
          material={materials.Decor}
          position={[2.613, 0.024, 0.122]}
          rotation={[-0.047, -0.175, -0.065]}
        />
        <mesh
          
          
          geometry={nodes.pCube158_Decor_0.geometry}
          material={materials.Decor}
          position={[0.297, 0, -5.191]}
        />
        <mesh
          
          
          geometry={nodes.pCube159_Decor_0.geometry}
          material={materials.Decor}
          position={[4.753, -0.354, -3.156]}
          rotation={[0.234, 1.38, -0.256]}
        />
        <mesh
          
          
          geometry={nodes.pCube160_Decor_0.geometry}
          material={materials.Decor}
          position={[8.564, -0.348, -1.135]}
          rotation={[0.364, 1.399, -0.369]}
        />
        <mesh
          
          
          geometry={nodes.polySurface32_Decor_0.geometry}
          material={materials.Decor}
          position={[1.867, -0.089, 0.165]}
          rotation={[0, 0.005, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube161_Decor_0.geometry}
          material={materials.Decor}
        />
        <mesh
          
          
          geometry={nodes.pCube161_Island_0.geometry}
          material={materials.Island}
        />
        <mesh
          
          
          geometry={nodes.pCube162_Decor_0.geometry}
          material={materials.Decor}
          position={[1.638, -0.063, 2.1]}
          rotation={[-0.055, 0.271, 0.02]}
        />
        <mesh
          
          
          geometry={nodes.pCube163_Decor_0.geometry}
          material={materials.Decor}
          position={[-1.999, 0, 2.143]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube164_Decor_0.geometry}
          material={materials.Decor}
          position={[0.422, 0, -0.053]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.polySurface33_Decor_0.geometry}
          material={materials.Decor}
          position={[0.418, 0, 0.853]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          
          
          geometry={nodes.pCube165_CLoud_0.geometry}
          material={materials.CLoud}
          position={[4.056, 0.233, 2.454]}
          scale={0.783}
        />
        <mesh
          
          
          geometry={nodes.pCube166_Island_Fade_0.geometry}
          material={materials.Island_Fade}
          position={[0, -0.51, 0]}
        />
      
    </a.group>
  )
}


export default Island;

